# _**Gaussian Elimination**_
We should import `numpy` since it has Matrix functionality written in C. Python isn't a fast language, so this will help with time performance.

In [854]:
import numpy as np
import pandas as pnds
np.set_printoptions(suppress=True)
rng = np.random.default_rng()

min, max = 10, 20
m, n = 6, 6
A = rng.random((m, n+1))
A = (max - min) * (A) + min
A = np.round(A)
# A[2][0:7] = 0
# A[3][0:7] = 0
print(A)

[[12. 15. 20. 13. 13. 18. 10.]
 [13. 13. 11. 10. 12. 20. 16.]
 [14. 19. 18. 19. 12. 13. 11.]
 [13. 18. 18. 14. 18. 18. 14.]
 [13. 16. 20. 20. 14. 15. 17.]
 [11. 14. 18. 15. 14. 18. 19.]]


## **Elementary Row Operations**
For a matrix, operations can be performed on the rows of the matrix that do not change the solutions of the matrix. These are called _elementary row operations_, and we can implement each of these operations as a function. 

In [855]:
def swap_rows(matrix, rA, rB):
    temp = [i for i in matrix[rA]]
    matrix[rA] = matrix[rB]
    matrix[rB] = temp

def add_rows(matrix, rA, rB, modifier=1):
    for i in range(0, len(matrix[rA])):
        matrix[rA][i] = matrix[rA][i] + modifier*matrix[rB][i]

def scale_row(matrix, r, a):
    matrix[r] *= a

We can test each of the functions.

In [856]:
# swap_rows(A, 0, 2)
# print(f"Swapping rows 1 and 3 \n {A}")

# add_rows(A, 0, 2, modifier=-1)
# print(f"\n Subtracting row 3 from row 1 \n {A}")

# scale_row(A, 0, 2)
# print(f"\n Scaling row 1 by a factor of 2 \n {A}")

However, elementary operations alone aren't enough Gaussian Elimination. In order to solve a system of linear equations using Gaussian Elimination, we need an algorithm that will apply these operations in a manner formats the matrix into _reduced row echelon form_ (RREF). 

For a matrix in RREF, the numbers on the rightmost column are the soultion to the system.

In [857]:
def solve_system(matrix):
    m, n = matrix.shape
    scale_row(matrix, 0, 1/matrix[0][0])
    q = m-1
    k = 0
    while True:
        if q < 0:
            q = m-1
            k += 1
            # print(k, pnds.DataFrame(np.round(A, 1)))
            if k < n-1:
                if matrix[k][k] == 0:
                    for i in range(k, m):
                        if matrix[i][k] != 0:
                            swap_rows(matrix, k, i)
                            print("break")
                            break
                else:
                    print("safe")
                if matrix[k][k] == 0:
                    k += 1
                    if k >= n-1:
                        break
                else:
                    scale_row(matrix, k, 1/matrix[k][k])
            else:
                break
        if q == k:
            q -= 1
        add_rows(matrix, q, k, modifier=matrix[q][k]*(-1))
        q -= 1

solve_system(A)
print(pnds.DataFrame(np.round(A, 2)))

safe
safe
safe
safe
safe
     0    1    2    3    4    5     6
0  1.0  0.0  0.0  0.0  0.0  0.0 -2.15
1  0.0  1.0  0.0  0.0  0.0  0.0 -0.06
2 -0.0 -0.0  1.0  0.0  0.0  0.0 -1.22
3  0.0  0.0  0.0  1.0  0.0  0.0  1.98
4  0.0  0.0  0.0  0.0  1.0  0.0  0.38
5  0.0  0.0  0.0  0.0  0.0  1.0  1.69
