# _**Gaussian Elimination**_
We should import `numpy` since it has Matrix functionality written in C. Python isn't a fast language, so this will help with time performance.

In [187]:
import numpy as np
import pandas as pnds
np.set_printoptions(suppress=True)
rng = np.random.default_rng()

min, max = 0, 1
m, n = 6, 6
A = rng.random((m, n+1))
A = (max - min) * (A) + min
A = np.round(A)
# A[2][0:7] = 0
# A[3][0:7] = 0
print(A)

# A = np.zeros((2, 3))
# A[0] = [2/3, -1/2, 1/3]
# A[1] = [-1/2, -1/6, 1]
# print(A)

[[0. 1. 0. 0. 0. 1. 1.]
 [1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0.]]


## **Elementary Row Operations**
For a matrix, operations can be performed on the rows of the matrix that do not change the solutions of the matrix. These are called _elementary row operations_, and we can implement each of these operations as a function. 

In [188]:
def swap_rows(matrix, rA, rB):
    temp = [i for i in matrix[rA]]
    matrix[rA] = matrix[rB]
    matrix[rB] = temp

def add_rows(matrix, rA, rB, modifier=1):
    for i in range(0, len(matrix[rA])):
        matrix[rA][i] = matrix[rA][i] + modifier*matrix[rB][i]

def scale_row(matrix, r, a):
    matrix[r] *= a

We can test each of the functions.

In [189]:
# swap_rows(A, 0, 2)
# print(f"Swapping rows 1 and 3 \n {A}")

# add_rows(A, 0, 2, modifier=-1)
# print(f"\n Subtracting row 3 from row 1 \n {A}")

# scale_row(A, 0, 2)
# print(f"\n Scaling row 1 by a factor of 2 \n {A}")

However, elementary operations alone aren't enough Gaussian Elimination. In order to solve a system of linear equations using Gaussian Elimination, we need an algorithm that will apply these operations in a manner formats the matrix into _reduced row echelon form_ (RREF). 

For a matrix in RREF, the numbers on the rightmost column are the soultion to the system.

In [190]:
def solve_system(matrix):
    m, n = matrix.shape
    # if matrix[0][0] != 0:
    # scale_row(matrix, 0, 1/matrix[0][0])
    q = m-1
    k = 0
    while True:
        if q < 0:
            q = m-1
            k += 1
            # print(k, pnds.DataFrame(np.round(A, 1)))
        if k < n-1:
            if matrix[k][k] == 0:
                for i in range(k, m):
                    if matrix[i][k] != 0:
                        swap_rows(matrix, k, i)
                        # print("break")
                        break
            # else:
            #     print("safe")
            if matrix[k][k] == 0:
                k += 1
                if k >= n-1:
                    break
            else:
                scale_row(matrix, k, 1/matrix[k][k])
        else:
            break
        if q == k:
            q -= 1
        if q >= 0:
            add_rows(matrix, q, k, modifier=matrix[q][k]*(-1))
        q -= 1

solve_system(A)
print(pnds.DataFrame(np.round(A, 2)))

     0    1    2    3    4    5    6
0  1.0  0.0  0.0  0.0  0.0 -1.0  0.0
1  0.0  1.0  0.0  0.0  0.0  1.0  1.0
2  0.0  0.0  1.0  0.0  0.0  0.0  1.0
3  0.0  0.0  0.0  1.0  0.0 -1.0 -2.0
4  0.0  0.0  0.0  0.0  1.0  1.0  1.0
5  0.0  0.0  0.0  0.0  0.0  0.0 -1.0
