# _**Gaussian Elimination**_
We should import `numpy` since it has Matrix functionality written in C. Python isn't a fast language, so this will help with time performance.

In [630]:
import numpy as np
import pandas as pnds
np.set_printoptions(suppress=True)
rng = np.random.default_rng()

min, max = 10, 20
m, n = 6, 6
A = rng.random((m, n+1))
A = (max - min) * (A) + min
A = np.round(A)
print(A)

[[14. 17. 10. 13. 12. 11. 18.]
 [15. 18. 19. 15. 15. 10. 11.]
 [16. 13. 13. 17. 16. 15. 19.]
 [17. 15. 10. 13. 14. 19. 12.]
 [19. 16. 16. 12. 16. 15. 18.]
 [12. 17. 12. 11. 11. 16. 18.]]


## **Elementary Row Operations**
For a matrix, operations can be performed on the rows of the matrix that do not change the solutions of the matrix. These are called _elementary row operations_, and we can implement each of these operations as a function. 

In [631]:
def swap_rows(matrix, rA, rB):
    temp = [i for i in matrix[rA]]
    matrix[rA] = matrix[rB]
    matrix[rB] = temp

def add_rows(matrix, rA, rB, modifier=1):
    for i in range(0, len(matrix[rA])):
        matrix[rA][i] = matrix[rA][i] + modifier*matrix[rB][i]

def scale_row(matrix, r, a):
    matrix[r] *= a

We can test each of the functions.

In [632]:
# swap_rows(A, 0, 2)
# print(f"Swapping rows 1 and 3 \n {A}")

# add_rows(A, 0, 2, modifier=-1)
# print(f"\n Subtracting row 3 from row 1 \n {A}")

# scale_row(A, 0, 2)
# print(f"\n Scaling row 1 by a factor of 2 \n {A}")

However, elementary operations alone aren't enough Gaussian Elimination. In order to solve a system of linear equations using Gaussian Elimination, we need an algorithm that will apply these operations in a manner formats the matrix into _reduced row echelon form_ (RREF). 

For a matrix in RREF, the numbers on the rightmost column are the soultion to the system.

In [633]:
def solve_system(matrix):
    m, n = matrix.shape
    scale_row(matrix, 0, 1/matrix[0][0])
    q = m-1
    k = 0
    while True:
        if q == k:
            q -= 1
        add_rows(matrix, q, k, modifier=matrix[q][k]*(-1))
        q -= 1
        if q < 0:
            q = m-1
            k += 1
            # print(k, pnds.DataFrame(np.round(A, 2)))
            if k < n-1:
                scale_row(matrix, k, 1/matrix[k][k])
            else:
                break

solve_system(A)
print(pnds.DataFrame(np.round(A, 2)))

     0    1    2    3    4    5      6
0  1.0  0.0  0.0  0.0  0.0  0.0 -17.18
1  0.0  1.0  0.0  0.0  0.0  0.0   5.90
2  0.0  0.0  1.0  0.0  0.0  0.0  -8.44
3 -0.0 -0.0 -0.0  1.0  0.0  0.0 -11.63
4  0.0  0.0  0.0  0.0  1.0  0.0  34.05
5  0.0  0.0  0.0  0.0  0.0  1.0  -1.34
